### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by naylaahmed** [rstudio/tinytex#385]
---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by naylaahmed** [comment]
Hello. I tired to install R packages recommended by its not happening. Error in loadNamespace(x) : there is no package called ‘tinytex’ I got this erro.Please let me know what should i do #385

**Comment by cderv** [comment]
Please can you edit the issue here and give details ? 

There is an issue template you can follow. Having R version and code you tried is the minimum we need as long as what you are trying to do. 

If you are trying to install Tinytex, the LaTeX distribution please do follow https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html
To install the R package, this is as any other R package. 

Project homepage will point you to information: https://yihui.org/tinytex/
