### ISSUE TITLE
WISH: Add https://yihui.org/tinytex/ to 'URL' in DESCRIPTION

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/tinytex#392]
Please consider adding <https://yihui.org/tinytex/> to the `URL` field in DESCRIPTION so that this link appears on <https://cran.r-project.org/web/packages/tinytex/index.html>.

**Comment by yihui** [comment]
Thanks for the suggestion! The link does appear on the CRAN page (in the package description instead of the `URL` field). On the other hand, usually I prefer a single ("canonical") URL in the `URL` field, i.e., the Github repo URL. Then in the Github repo, I'll provide links to other relevant sites. Users won't need to think which link to open when reading the CRAN page.

The link https://yihui.org/tinytex/ is mostly about the LaTeX distribution TinyTeX and less about the R package **tinytex**, which is also a reason why I didn't include it in `URL`.

If you still think it would be a good idea to include this URL in the `URL` field, I certainly can do it. I don't really have a strong opinion.

**Comment by HenrikBengtsson** [comment]
Got it. I got no strong opinion here, and it sounds like you already had a strategy and though behind this. I just thought it might have been forgotten.
