### ISSUE TITLE
internal fmtutil calling on windows does not work

### ISSUE THREAD

**Issue by cderv** [rstudio/tinytex#427]
````r
> tinytex:::fmtutil()
...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:941: ...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:864: no appropriate script or program found: fmtuti~1
````

This is not an issue with `tlmgr_update` which call this function because we set `stdout = FALSE` 
````r
> tinytex:::fmtutil(stdout = FALSE)
```` 
which hide the error

So something is not right. 

````r
> system2("fmtutil-sys", "--all")
...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:941: ...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:864: no appropriate script or program found: fmtuti~1
> system("fmtutil-sys.exe --all")
...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:941: ...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:864: no appropriate script or program found: fmtuti~1
[1] 1
````

However, `processx::run("fmtutil-sys", "--all")` works ok, and `sys::exec_wait("fmtutil-sys", "--all")` also. 

Found while looking at https://github.com/quarto-dev/quarto-cli/issues/7252 (which means that solution in TinyTeX was not working on windows 🤔 )

This is probably a shell thing. Other commands that works 
* `xfun:::powershell("fmtutil-sys --all")`
* `shell("fmtutil-sys --all")`

Not sure how to tweak `system2()` to solve this problem 🤔

**Comment by yihui** [comment]
That's interesting. Not sure why `system2()` preferred using the shortened path. Does `system('fmtutil-sys --all')` work?

**Comment by cderv** [comment]
> Does system('fmtutil-sys --all') work?

No it doesn't 
````r
> system('fmtutil-sys --all')
...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:941: ...\chris\AppData\Roaming\TinyTeX\bin\windows\runscript.tlu:864: no appropriate script or program found: fmtuti~1
[1] 1
````

**Comment by cderv** [comment]
> Not sure why system2() preferred using the shortened path

Maybe because R `Sys.which()` does use it (because of the `-` ? ) 🤔 

````
> Sys.which("fmtutil-sys")
                                                              fmtutil-sys 
"C:\\Users\\chris\\AppData\\Roaming\\TinyTeX\\bin\\windows\\FMTUTI~1.EXE" 
````

**Comment by yihui** [comment]
I think this is because `system()` and `system2()` will use shortened paths when executing commands: https://github.com/wch/r-source/blob/635a672151a18a0e475986af592fab59e7479a9b/src/gnuwin32/run.c#L141 But TeX Live can't deal with shortened paths.

Perhaps we need to switch to `shell()` when a command's path would be shortened. Let me first ask on r-devel why paths need to be shortened (I know one reason is to avoid spaces in paths).

**Comment by yihui** [comment]
BTW, it will be nice if R could provide an option to disable shortening paths, but this might also be solved on TeX Live's end if TeX Live could recognize [short paths](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names). Cc @norbusan: you don't need to read the full thread here---the problem that we ran into was that calling `fmutil-sys.exe` on Windows using its short path `FMTUTI~1.EXE` doesn't work. I wonder if there's a chance to fix it on TeX Live's side. Thanks!

**Comment by norbusan** [comment]
@yihui I am not sure how we should fix that. Do you suggest that instead of calling `system("fmtutil.exe ...")` we should call `system("FMTUTI~1.EXE ,,,")`?

BTW, what happens if there are multiple fmtutil? How do we know which one is the correct one?

**Comment by yihui** [comment]
No, I'm not suggesting that. From my limited understanding of `runscript.tlu`, the error came from the line 864: https://tug.org/svn/texlive/trunk/Master/bin/windows/runscript.tlu?revision=68579&view=markup#l864 When `fmutil-sys.exe` was invoked by the name `FMTUTI~1.EXE` (which should be valid on Windows), `find_texmfscript()` was unable to find the correct executable.

As I said, this seems to be a recent change, because no one has reported this problem for the past few years. I could be wrong and this may be a certain coincidence (in other words, it might have existed for a long time but didn't surface until another problem occurred).

> BTW, what happens if there are multiple fmtutil? How do we know which one is the correct one?

I don't know the answer in general, but in our case, we are calling a specific `bin/windows/fmtutil-sys.exe` in the root directory of TinyTeX.

**Comment by yihui** [comment]
> When `fmutil-sys.exe` was invoked by the name `FMTUTI~1.EXE` (which should be valid on Windows), `find_texmfscript()` was unable to find the correct executable.

@norbusan This was also verified by an R core team member: https://stat.ethz.ch/pipermail/r-devel/2023-October/082979.html They said they wouldn't "fix" it in R, so our only hope is that TeX Live would accept short paths of commands.

**Comment by norbusan** [comment]
@yihui sorry for the long silence, I lost track of that.

What about if you call `fmtutil.exe --sys ...other arg...` ? That should result in an un-shortened `fmtutil.exe` call and all should be fine?

**Comment by yihui** [comment]
@norbusan This is definitely a workaround but only because the name `fmtutil` has less than 8 characters. I'm not sure which executables would first go through `runscript.tlu`. There might be other ones that have more than 8 characters such as `kpsewhich.exe`. So it will be nice if `runscript.tlu` can accept short paths.

**Comment by yihui** [comment]
Thank you very much! I have changed `fmtutil-sys` to `fmtutil --sys` (also `updmap-sys` to `updmap --sys`) as you suggested. I think we are good for now.

**Comment by norbusan** [comment]
@yihui Thanks to Akira and Luigi, we have updated runscript DLL to get the long name by itself.
So with a current/uptodate TeX Live it should now work even with `fmtutil-sys`.
Could you try and report back? Thanks

**Comment by yihui** [comment]
@norbusan I can confirm that the new `runscript.dll` works perfectly now. Thank you and Akira/Luigi so much!

However, a deeper problem is that TeX Live doesn't work when installed to a directory that contains non-ASCII characters in its path, as [Akira mentioned in the mailing list](https://tug.org/pipermail/tex-live/2023-November/049634.html). It will be great if this limitation can be removed. In the meantime, I'll also try to come up with a install path that doesn't contain non-ASCII characters.

**Comment by norbusan** [comment]
Hi @yihui 
Thanks for confirmation of the fix, much appreciated!

Concerning the non-ASCII characters in its path, I really don't know whether this is easy to fix or not. I will discuss with the Japanese Development Team who often helps with fixing these kinds of things.
